singulars:
  smithing:
    basicForge:
      name: Basic Forge
      desc: An entry-level forge, ideal for crafting straightforward items.
    advancedForge:
      name: Advanced Forge
      desc: A more sophisticated forge, perfect for fashioning intricate and higher-quality creations.
    frozenForge:
      name: Frozen Forge
      desc: A forge made out of ice with small carvings of penguins all over it.
    underwaterForge:
      name: Underwater Forge (Basic)
      desc: The underwater forge is operated by hot steam geysers providing enough heat to melt metal.
    cursedForge:
      name: Cursed Forge (Advanced)
      desc: The cursed forge draws its powerful flames from the spirits around it, unfortunately this comes at a price. Best not to use it too much.
    heatstrokeMetalworks:
      name: Heatstroke Metalworks (Advanced)
      desc: The strong and acclaimed forge of the Myriadian Arc. It boasts a heat that you can feel around it even in the desert.
  cooking:
    basicKitchen:
      name: Basic Kitchen
      desc: A modest kitchen setup, where you can prepare simple and wholesome meals.
    advancedKitchen:
      name: Advanced Kitchen
      desc: A well-equipped kitchen, suitable for gourmet cooking and culinary experiments.
    underwaterKitchen:
      name: Underwater Kitchen (Basic)
      desc: This kitchen is equipped with various cooking tools adjusted to making food underwater.
    eberhartMansionKitchen:
      name: Eberhart Mansion Kitchen (Advanced)
      desc: The Eberhart family gives to those who give to others. Proof of your dedication to the local soup kitchen is more than enough reason for them to open their doors and assist you in their shared kitchen space.
    azurazeraKitchen:
      name: Alight Kitchen (Basic)
      desc: A community kitchen with some chefs trying to share their cooking experiences with one another to improve.
    cursedKitchen:
      name: Cursed Kitchen (Advanced)
      desc: The cursed kitchen has everything you need to help cook a dish, if only the stove would stay a consistent temperature, and the water stayed running.
  crafting:
    basicWorkshop:
      name: Basic Workshop
      desc: A basic workshop setup, designed for crafting simple and practical items.
    advancedWorkshop:
      name: Advanced Workshop
      desc: An advanced workshop, equipped for crafting complex and versatile creations.
    tidalWorkshop:
      name: Tidal Workshop (Advanced)
      desc: A workshop that's always influenced by current. It has all the tools needed for crafting things.
    cursedWorkshop:
      name: Cursed Workshop (Advanced)
      desc: The cursed workshop seems ordinary at first but it smells of sulfur, rot, and a hint of lemon. It is indeed cursed.
  trinketry:
    basicTrinketryBench:
      name: Basic Trinketry Bench
      desc: A working bench, designed for cutting gems and making simple trinkets.
    ruinedTrinketryBench:
      name: Ruined Trinketry Bench (Basic)
      desc: In the ruins of Winter's End, an ancient trinketry bench sits covered with moss and mushrooms.
    advancedTrinketryBench:
      name: Advanced Trinketry Bench
      desc: A modest bench, filled with lenses, sandpaper, and the other tool of a journeyman trinket-maker.
    erdwissTrinketryFactory:
      name: Erdwiss Trinketry Factory (Advanced)
      desc: The ETF has some of the finest machines imported from Galeforge for use in cutting gems.
    granularFacetingFacility:
      name: Granular Faceting Facility (Advanced)
      desc: An outstanding trinketry facility that gathers some of the best followers of the art of gemistry around.
  carpentry:
    basicSawmill:
      name: Basic Sawmill
      desc: A rudimentary timber processing facility, where logs are transformed into basic lumber.
    advancedSawmill:
      name: Advanced Sawmill
      desc: An advanced timber processing mill, capable of producing higher-quality lumber with precision and efficiency.
    barbantokSawmill:
      name: Sawmill of Barbantok (Basic)
      desc: A sawmill that is said to be haunted by the ghost of Barbantok, a legendary carpenter who was known for his exceptional craftsmanship.
    underwaterSawmill:
      name: Underwater Sawmill (Basic)
      desc: A sawmill that's perfect for working with woodlike corals, but also provides tools to make any logs into planks.
    sawInHalfMill:
      name: Saw-in-half mill (Advanced)
      desc: The halfling sawmill is a marvel of engineering, relying on the flow of water through an underwater aqueduct and a sophisticated water wheel.
    cursedSawmill:
      name: Cursed Sawmill (Advanced)
      desc: The cursed sawmill spins a saw so fast that you fear it will break free. At times you feel it pulling toward you rather than the logs being cut.
  tailoring:
    basicLoom:
      name: Basic Loom
      desc: A modest workshop, housing a sturdy loom and a well-worn sewing table, is filled with an assortment of fabrics and tools, perfect for budding tailors eager to learn the art of garment-making.
    advancedLoom:
      name: Advanced Loom
      desc: A well-appointed workshop, housing a state-of-the-art loom and an elegant sewing table, is filled with a curated selection of premium fabrics and specialized tools, perfect for experienced tailors seeking to craft exquisite garments.
  cosmetics:
    barber:
      name: Barber
      desc: A barber who can style your hair to a different one.
    wardrobe:
      name: Wardrobe
      desc: Access to your wardrobe, so you can change your looks to any cosmetics you might own.
maps:
  tiers:
    "basic": Basic
    "advanced": Advanced
    "legendary": Legendary
    "mythic": Mythic