singulars:
  smithing:
    basicForge:
      name: Základní kovárna
      desc: Kovárna pro začátečníky, ideální pro výrobu jednoduchých předmětů.
    advancedForge:
      name: Pokročilá kovárna
      desc: Sofistikovanější kovárna, ideální pro výrobu složitých a kvalitnějších
        výtvorů.
    underwaterForge:
      name: Podvodní kovárna (základní)
      desc: Podvodní kovárna je poháněna horkými parními gejzíry, které poskytují
        dostatek tepla k roztavení kovu.
    frozenForge:
      name: Zamrzlá Kovárna
      desc: Chatrč vytesaná z ledu, pokrytá rytinami zobrazujícími tučňáky.
    heatstrokeMetalworks:
      name: Úpal kovů (pokročilý)
      desc: Silná a uznávaná kovárna Myriadského oblouku. Pyšní se žárem, který cítíte
        kolem ní i v poušti.
    cursedForge:
      desc: Prokletá kovárna čerpá své mocné plameny z duchů kolem sebe, bohužel to
        má svou cenu. Nejlepší je ji příliš nepoužívat.
      name: Prokletá kovárna (Pokročilá)
  cooking:
    basicKitchen:
      name: Základní kuchyně
      desc: Skromné kuchyňské zařízení, kde si můžete připravit jednoduchá a zdravá
        jídla.
    advancedKitchen:
      name: Pokročilá kuchyně
      desc: Dobře vybavená kuchyň, vhodná pro gurmánské vaření a kulinářské experimenty.
    underwaterKitchen:
      name: Podvodní kuchyně (základní)
      desc: Tato kuchyně je vybavena různým kuchyňským náčiním přizpůsobeným pro přípravu
        jídla pod vodou.
    eberhartMansionKitchen:
      name: Kuchyně v Eberhart Mansion (pokročilá)
      desc: Rodina Eberhartových dává těm, kteří dávají ostatním. Důkaz vaší oddanosti
        místní polévkové kuchyni je pro ně více než dostatečným důvodem, aby vám otevřili
        dveře a pomohli vám ve sdílené kuchyni.
    azurazeraKitchen:
      name: Zapálená kuchyně (základní)
      desc: Komunitní kuchyně s kuchaři, kteří se snaží sdílet své kulinářské zkušenosti
        a zlepšovat se.
    cursedKitchen:
      name: Prokletá kuchyně (Pokročilá)
      desc: Prokletá kuchyně má vše, co potřebujete k uvaření jídla, jen kdyby sporák
        udržoval stálou teplotu a voda tekla.
  crafting:
    basicWorkshop:
      name: Základní dílna
      desc: Základní dílenské vybavení, určené pro výrobu jednoduchých a praktických
        předmětů.
    advancedWorkshop:
      name: Pokročilá dílna
      desc: Pokročilá dílna vybavená pro tvorbu složitých a všestranných výtvorů.
    tidalWorkshop:
      name: Tidal dílna (pokročilá)
      desc: Dílna, která je vždy ovlivněna současností. Má veškeré nářadí potřebné
        k tvoření.
    cursedWorkshop:
      name: Prokletá dílna (Pokročilá)
      desc: Prokletá dílna se zpočátku zdá obyčejná, ale voní sírou, hnilobou a náznakem
        citronu. Je skutečně prokletá.
  trinketry:
    basicTrinketryBench:
      desc: Pracovní stůl určený pro broušení drahokamů a výrobu jednoduchých drobností.
      name: Základní stůl na šperky
    ruinedTrinketryBench:
      name: Zničený pracovní stůl na šperky (základní)
      desc: Starožitný stůl na šperky pokrytý mechem a houbami, pozůstalý mezi ruinami
        Zimního konce.
    advancedTrinketryBench:
      name: Pokročilý stůl na šperky
      desc: Skromný stůl plný čoček, brusného papíru a dalšího nářadí tovaryše, který
        se zabýval výrobou drobností.
    erdwissTrinketryFactory:
      name: Továrna na šperky (Pokročilá)
      desc: ETF má jedny z nejlepších strojů dovezených z Galeforge pro použití při
        řezání drahokamů.
    granularFacetingFacility:
      name: Zařízení pro granulární fazetování (Pokročilé)
      desc: Vynikající zařízení na drobnosti které shromažďuje některé z nejlepších
        stoupenců umění gemie v okolí.
  carpentry:
    basicSawmill:
      name: Základní pila
      desc: Základní zařízení na zpracování dřeva, kde se klády přeměňují na základní
        řezivo.
    advancedSawmill:
      name: Pokročilá pila
      desc: Pokročilé zařízení na zpracování dřeva schopné vyrábět řezivo vyšší kvality
        s přesností a efektivitou.
    barbantokSawmill:
      name: Pila v Barbarské osadě (základní)
      desc: Pila, o které se říká, že ji pronásleduje duch Barbarské osady, legendárního
        tesaře, který byl známý svým výjimečným řemeslným zpracováním.
    underwaterSawmill:
      name: Podvodní pila (základní)
      desc: Pila, která je ideální pro práci s dřevitými korály, ale také poskytuje
        nástroje k přeměně jakýchkoli klád na prkna.
    sawInHalfMill:
      name: Půlčíková pila (pokročilá)
      desc: Půlčíková pila je zázrak inženýrství, spoléhající se na tok vody podvodním
        akvaduktem a sofistikované vodní kolo.
    cursedSawmill:
      name: Prokletá pila (Pokročilá)
      desc: Prokletá pila točí pilu tak rychle, že se bojíte, že se uvolní. Občas
        cítíte, jak k vám táhne ona sama, a ne řezané klády.
  tailoring:
    advancedLoom:
      name: Pokročilý tkalcovský stav
      desc: Dobře vybavená dílna s nejmodernějším tkalcovským stavem a elegantním
        šicím stolem je plná pečlivě vybraných prémiových látek a specializovaných
        nástrojů, ideálních pro zkušené krejčí, kteří chtějí šít nádherné oděvy.
    basicLoom:
      name: Základní tkalcovský stav
      desc: Skromná dílna s robustním tkalcovským stavem a opotřebovaným šicím stolem
        je plná různých látek a nástrojů, ideálních pro začínající krejčí, kteří se
        chtějí naučit umění oděvní výroby.
  cosmetics:
    barber:
      name: Holič
      desc: Holič, který vám může upravit vlasy na jakýkoliv způsob.
    wardrobe:
      name: Šatník
      desc: Přístup k vašemu šatníku, abyste si mohli změnit vzhled s využitím jakékoli
        kosmetiky, kterou vlastníte.
  misc:
    mysteriousMerchant:
      name: Tajemný obchodník
      desc: Stínová postava, která nabízí exotické služby.
maps:
  tiers:
    "basic": Základní
    "advanced": Pokročilá
    "legendary": Legendární
    "mythic": Mýtický
