singulars:
  smithing:
    basicForge:
      name: Einfache Schmiede
      desc: Eine Beginnerschmiede, ideal für die Herstellung von einfachen Gegenständen.
    advancedForge:
      name: Fortgeschrittene Schmiede
      desc: Eine ausgefeilte Schmiede, perfekt um komplizierte und hochqualitative
        Kreationen zu erschaffen.
    frozenForge:
      name: Gefrorene Schmiede
      desc: Eine Schmiede aus Eis, in der überall Pinguine eingeschnitzt sind.
    underwaterForge:
      name: Unterwasserschmiede (Einfach)
      desc: Die Unterwasser-Schmiede wird von heißen Dampfontänen betrieben, die genug
        Wärme liefern, um Metall zu schmelzen.
    heatstrokeMetalworks:
      desc: Die mächtige und hochgerühmte Schmiede des Myriadianischen Bogens. Ihre
        Hitze ist noch in ihrer Umgebung zu spüren – selbst mitten in der Wüste.
      name: Hitzschlag-Metallwerk (Fortgeschritten)
    cursedForge:
      name: Verfluchte Schmiede (Fortgeschritten)
      desc: Die verfluchte Schmiede speist ihre mächtigen Flammen aus den umherirrenden
        Geistern – doch dieser Kraft wohnt ein Preis inne. Es ist wohl besser, sie
        nicht allzu oft zu nutzen.
  cooking:
    basicKitchen:
      name: Gewöhnliche Küche
      desc: Eine bescheidene Küchenausstattung mit der du einfache und bekömmliche
        Gerichte fertigen kannst.
    advancedKitchen:
      name: Fortgeschrittene Küche
      desc: Eine gut ausgestattete Küche, gemacht für Gourmetküche und kulinarische
        Experimente.
    underwaterKitchen:
      name: Unterwasserküche (Einfach)
      desc: Die Küche ist mit verschiedenen Kochutensilien ausgestattet, die speziell
        für das Zubereiten von Speisen unter Wasser angepasst sind.
    eberhartMansionKitchen:
      name: Eberhart Villa Küche (Fortgeschritten)
      desc: Die Familie Eberhart gibt jenen, die auch anderen etwas geben. Der Beweis
        deines Engagements für die örtliche Suppenküche ist mehr als Grund genug für
        sie, dir ihre Türen zu öffnen und dir Zugang zu ihrer gemeinschaftlich genutzten
        Küche zu gewähren.
    azurazeraKitchen:
      name: Alight Küche (Einfach)
      desc: Eine Gemeinschaftsküche, in der einige Köche versuchen, ihre Kocherfahrungen
        miteinander zu teilen, um sich zu verbessern.
    cursedKitchen:
      name: Verfluchte Küche (Fortgeschritten)
      desc: Die verfluchte Küche hat alles, was du zum Kochen eines Gerichts brauchst
        – wenn nur der Herd eine konstante Temperatur halten und das Wasser nicht
        ständig versiegen würde.
  crafting:
    basicWorkshop:
      name: Einfache Werkstatt
      desc: Eine einfache Werkstatt, gemacht um einfache und praktische Gegenstände
        herzustellen.
    advancedWorkshop:
      name: Fortgeschrittene Werkstatt
      desc: Eine fortgeschrittene Werkstatt, ausgestattet um komplexe und vielseitige
        Kreationen zu erschaffen.
    tidalWorkshop:
      name: Gezeitenwerkstatt (Fortgeschritten)
      desc: Eine Werkstatt, die stets vom Strom beeinflusst wird. Sie ist mit allen
        Werkzeugen ausgestattet, die für das Handwerk benötigt werden.
    cursedWorkshop:
      desc: Die verfluchte Werkstatt sieht zunächst völlig normal aus, doch in ihr
        liegt ein Geruch von Schwefel, Verwesung und einem Hauch Zitrone. Sie ist
        ohne Zweifel verflucht.
      name: Verfluchte Werkstatt (Fortgeschritten)
  carpentry:
    basicSawmill:
      name: Einfaches Sägewerk
      desc: Eine rudimentäres Holzverarbeitungsgebäude, in dem Stämme zu einfachem
        Bauholz geschnitten werden.
    barbantokSawmill:
      name: Sägewerk von Barbantok (Einfach)
      desc: Ein Sägewerk, das von dem Geist von Barbantok heimgesucht werden soll,
        ein legendärer Tischler, der für seine außergewöhnliche Handwerkskunst bekannt
        war.
    underwaterSawmill:
      name: Unterwassersägewerk (Einfach)
      desc: Eine Sägewerk, das perfekt für die Verarbeitung von holzähnlichen Korallen
        geeignet ist, aber auch Werkzeuge bietet, um jeden Stamm in Bretter zu verwandeln.
    advancedSawmill:
      desc: Ein modernes Holzverarbeitungswerk, das in der Lage ist, mit Präzision
        und Effizienz hochwertiges Bauholz zu produzieren.
      name: Fortgeschrittenes Sägewerk
    sawInHalfMill:
      desc: 'Die Halblings-Sägemühle ist ein Wunder der Ingenieurskunst: Sie nutzt
        den Wasserstrom eines Unterwasser-Aquädukts und ein raffiniertes Wasserrad
        als Antrieb.'
      name: Halbling Sägewerk (Fortgeschritten)
    cursedSawmill:
      desc: Das verfluchte Sägewerk treibt eine Säge so schnell an, dass du fürchtest,
        sie könnte sich aus ihrer Verankerung lösen. Manchmal hast du das Gefühl,
        dass sie eher zu dir hingezogen wird als zu den Stämmen, die sie zerschneidet.
      name: Verfluchtes Sägewerk (Fortgeschritten)
  cosmetics:
    barber:
      name: Friseur
      desc: Ein Friseur, der deinen Haarschnitt zu einem anderen umwandeln kann.
    wardrobe:
      name: Garderobe
      desc: Zugang zu deiner Garderobe, damit du dein Aussehen mit deinen Kosmetikgegenständen
        ändern kannst.
  tailoring:
    basicLoom:
      name: Einfacher Webstuhl
      desc: Eine bescheidene Werkstatt, die einen robusten Webstuhl und einen gut
        gebrauchten Nähtisch beherbergt, ist gefüllt mit einer Sammlung von Stoffen
        und Werkzeugen – ideal für angehende Schneider, die begierig darauf sind,
        die Kunst des Kleidermachens zu erlernen.
    advancedLoom:
      name: Fortgeschrittener Webstuhl
      desc: Eine gut ausgestattete Werkstatt, die einen hochmodernen Webstuhl und
        einen eleganten Nähtisch beherbergt, ist gefüllt mit einer sorgfältig ausgewählten
        Sammlung erstklassiger Stoffe und spezialisierter Werkzeuge – ideal für erfahrene
        Schneider, die darauf aus sind, exquisite Kleidungsstücke zu fertigen.
  trinketry:
    basicTrinketryBench:
      name: einfache Kunsthandwerksbank
      desc: Diese Werkbank ist die perfekte Basis für Juweliere und Handwerker, die
        Edelsteine schneiden und Schmuck kreieren wollen.
    advancedTrinketryBench:
      desc: Eine bescheidene Werkbank, gefüllt mit Linsen, Schleifpapier und den anderen
        Werkzeugen eines journeyman Schmuckhandwerkers.
      name: Fortgeschrittene Kunsthandwerksbank
    erdwissTrinketryFactory:
      desc: Die ETF besitzt einige der besten Maschinen, die aus Galgenschmied importiert
        wurden, um Edelsteine zu schneiden.
      name: Erdweis Kunsthandwerk-Fabrik (Fortgeschritten)
    ruinedTrinketryBench:
      desc: Zwischen den zerfallenen Mauern von Winter’s End steht eine alte Kunsthandwerksbank,
        von Moos und Pilzen umschlungen.
      name: Zerschlissene Kunsthandwerksbank (Einfach)
    granularFacetingFacility:
      name: Granulare Facettieranlage (Fortgeschritten)
      desc: Eine außergewöhnliche Schmuckwerkstatt, in der sich einige der besten
        Anhänger des Kunsthandwerks versammeln.
  misc:
    mysteriousMerchant:
      name: Mysteriöser Händler
      desc: Eine schattenhafte Gestalt, die exotische Dienstleistungen anbietet.
maps:
  tiers:
    'basic': Einfach
    'advanced': Fortgeschritten
    'legendary': Legendär
    'mythic': Mystisch
