singulars:
  smithing:
    basicForge:
      name: Podstawowa Kuźnia
      desc: Kuźnia dla początkujących, idealna do wytwarzania prostych przedmiotów.
    advancedForge:
      name: Zaawansowana Kuźnia
      desc: Bardziej wyszukana kuźnia, idealna do tworzenia skomplikowanych i wyższej
        jakości przedmiotów.
    underwaterForge:
      name: Podwodna Kuźnia (Podstawowa)
      desc: Podwodna kuźnia jest obsługiwana przez gejzery gorącej pary zapewniające
        ciepło do stopienia metalu.
    frozenForge:
      name: Zamarznięta Kuźnia
      desc: Kuźnia wykonana z lodu, pokryta małymi rzeźbami pingwinów.
  cooking:
    basicKitchen:
      name: Podstawowa Kuchnia
      desc: Skromna zabudowa kuchenna, w której można przygotować proste i zdrowe
        posiłki.
    advancedKitchen:
      name: Zaawansowana Kuchnia
      desc: Dobrze wyposażona kuchnia, odpowiednia do gotowania i eksperymentów kulinarnych
        dla smakoszy.
    underwaterKitchen:
      name: Podwodna Kuchnia (Podstawowa)
      desc: Ta kuchnia wyposażona w różne narzędzia kuchenne przystosowane do przygotowywania
        potraw pod wodą.
    eberhartMansionKitchen:
      name: Kuchnia Eberhartów (Zaawansowana)
      desc: Rodzina Eberhartów daje tym, którzy dają innym. Dowód twojego poświęcenia
        w lokalną kuchnię w Azurazerze jest dla nich więcej niż wystarczającym powodem,
        aby otworzyć drzwi i pozwolić ci korzystać ze wspólnej przestrzeni kuchennej.
    azurazeraKitchen:
      name: Wspólna Kuchnia (Podstawowa)
      desc: Kuchnia wspólnotowa, w której szefowie kuchni dzielą się ze sobą swoimi
        doświadczeniami kulinarnymi, aby doskonalić swoje umiejętności.
  crafting:
    basicWorkshop:
      name: Podstawowy Warsztat
      desc: Podstawowy zestaw warsztatowy, przeznaczony do tworzenia prostych i praktycznych
        przedmiotów.
    advancedWorkshop:
      name: Zaawansowany Warsztat
      desc: Zaawansowany warsztat, wyposażony do tworzenia skomplikowanych i wszechstronnych
        przedmiotów.
    tidalWorkshop:
      desc: Warsztat, który zawsze jest pod wpływem prądu. Posiada wszystkie narzędzia
        potrzebne do tworzenia rzeczy.
      name: Pływowy Warsztat (Zaawansowany)
  cosmetics:
    wardrobe:
      name: Garderoba
      desc: Dostęp do twojej garderoby, dzięki czemu możesz zmienić swój wygląd na
        dowolne elementy kosmetyczne, które masz.
    barber:
      name: Fryzjer
      desc: Fryzjer, który może ułożyć Ci inną fryzurę.
  carpentry:
    basicSawmill:
      name: Podstawowy Tartak
      desc: Prymitywny zakład obróbki drewna, w którym kłody przekształcane są w podstawową
        tarcicę.
    advancedSawmill:
      name: Zaawansowany Tartak
      desc: Zaawansowany zakład przetwórstwa drewna, zdolny do produkcji tarcicy wyższej
        jakości z precyzją i wydajnością.
    barbantokSawmill:
      name: Tartak w Barbantok (Podstawowy)
      desc: Tartak, o którym mówi się, że nawiedza go duch Barbantoka, legendarnego
        stolarza słynącego z wyjątkowej sztuki swojego fachu.
    underwaterSawmill:
      name: Podwodny Tartak (Podstawowy)
      desc: Tartak, który jest idealny do pracy z koralami drewnopodobnymi, ale zapewnia
        również narzędzia do przekształcania dowolnych kłód w deski.
    sawInHalfMill:
      desc: Tartak niziołków to cud inżynierii, a jego działanie opiera się na przepływie
        wody przez podwodny akwedukt oraz zaawansowane koło wodne.
      name: Tartak Przetnij-W-Pół (Zaawansowany)
  tailoring:
    advancedLoom:
      desc: Dobrze wyposażony warsztat, mieszczący najnowocześniejsze krosno i elegancki
        stół do szycia, wypełniony jest wyselekcjonowaną jakością tkanin i specjalistycznych
        narzędzi, idealnych dla doświadczonych krawców pragnących tworzyć wykwintne
        ubrania.
      name: Zaawansowana Tkalnia
    basicLoom:
      desc: Skromny warsztat, w którym znajduje się solidne krosno i wysłużony stół
        do szycia, wypełniony jest asortymentem tkanin i narzędzi, idealnych dla początkujących
        krawców chcących nauczyć się sztuki szycia odzieży.
      name: Podstawowa Tkalnia
  trinketry:
    erdwissTrinketryFactory:
      desc: Fabryka błyskotek w Erdwiss posiada jedne z najlepszych maszyn importowanych
        z Galeforge do obróbki klejnotów.
      name: Fabryka Błyskotek (Zaawansowana)
    basicTrinketryBench:
      name: Podstawowa Pracownia Jubilerska
      desc: Warsztat roboczy, przeznaczony do obróbki klejnotów i tworzenia prostych
        drobiazgów.
    advancedTrinketryBench:
      name: Zaawansowana Pracownia Jubilerska
      desc: Skromny warsztat, wypełniony soczewkami, papierem ściernym i innymi narzędziami
        czeladnika bibelotów.
    ruinedTrinketryBench:
      name: Zrujnowana Pracownia Jubilerska (Podstawowa)
      desc: W ruinach Końca Zimy starożytny warsztat z bibelotami jest pokryty mchem
        i grzybami.
maps:
  tiers:
    'basic': Podstawowy
    'advanced': Zaawansowany
    'legendary': Legendarny
    'mythic': Mityczny
