singulars:
  carpentry:
    underwaterSawmill:
      desc: Saha, joka on täydellinen vedenalaisten puumateriaalien, kuten korallien,
        jalostukseen. Soveltuu myös normaalien tukkien jalostamiseen.
      name: Vedenalainen saha (simppeli)
    basicSawmill:
      name: Simppeli saha
      desc: Alkeellinen puunjalostuskäyttöön tarkoitettu saha, jossa tukeista voi
        jalostaa puutavaraa.
    advancedSawmill:
      name: Edistynyt saha
      desc: Edistynyt puunjalostustehdas, jossa on mahdollista tuottaa korkeampilaatuista
        puutavaraa.
    barbantokSawmill:
      name: Barbantokin saha (simppeli)
      desc: Barbantokin sanotaan olleen tarunhohtoinen puuseppä, ja hänen haamunsa
        haamun huhutaan yhä kummittelevan tällä sahalla.
    sawInHalfMill:
      name: Puolituissaha (edistynyt)
      desc: Tämä puolituisten saha on ihmeellinen suunnittelutaidon näyte, joka perustuu
        veden voiman ohjaamiseen vedenalaisen putkiston läpi pyörittämään monimutkaista
        vesiratasta.
  smithing:
    basicForge:
      name: Simppeli ahjo
      desc: Aloittelijatason ahjo, joka sopii ihanteellisesti yksinkertaisten esineiden
        valmistukseen.
    advancedForge:
      name: Edistynyt ahjo
      desc: Kehittyneempi ahjo, joka soveltuu laadukkaampien luomusten valmistukseen.
    frozenForge:
      name: Jäätynyt ahjo
      desc: Jäästä valmistettu ahjo, jossa on joka puolella pieniä kaiverruksia pingviineistä.
    underwaterForge:
      name: Vedenalainen ahjo (simppeli)
      desc: Vedenalaista ahjoa lämmittävät sen uumenissa olevat kuumat lähteet, jotka
        tuottavat riittävästi lämpöä metallin sulattamiseen.
    cursedForge:
      name: Kirottu ahjo (edistynyt)
  cooking:
    basicKitchen:
      name: Simppeli keittiö
      desc: Vaatimaton keittiö, jossa voit valmistaa yksinkertaisia ruoka-annoksia.
    advancedKitchen:
      name: Edistynyt keittiö
      desc: Hyvin varusteltu keittiö, joka sopii hienostuneempaan kokkailuun.
    underwaterKitchen:
      name: Vedenalainen keittiö (simppeli)
      desc: Tämä keittiö on varustettu erikoisilla keittiövälineillä, jotka on suunniteltu
        vedenalaiseen ruoanlaittoon.
    eberhartMansionKitchen:
      name: Eberhartin kartanon keittiö (edistynyt)
      desc: Eberhartin perheellä on tapana laittaa hyvä kiertämään. Mikäli voit todistaa
        raataneesi töitä paikallisella soppatykillä, mitä luultavimmin Eberhartin
        perhe avustaa sinua heidän yhteisessä keittiötilassaan.
    azurazeraKitchen:
      name: Valaistu keittiö (Simppeli)
      desc: Yhteisöllinen keittiö, jossa kokit yrittävät jakaa ruoanlaittokokemuksiaan
        toistensa kanssa parantaakseen taitojaan.
    cursedKitchen:
      name: Kirottu keittiö (edistynyt)
  crafting:
    basicWorkshop:
      name: Simppeli työpaja
      desc: Vaatimaton työpaja, jossa on mahdollista luoda yksinkertaisia ja käytännöllisiä
        esineitä.
    advancedWorkshop:
      name: Edistynyt työpaja
      desc: Edistynyt työpaja on varusteltu monimutkaisten luomusten tekemiseen.
    tidalWorkshop:
      name: Vuorovesityöpaja (edistynyt)
      desc: Työpaja, johon vuorovedet vaikuttavat alati. Työpajasta löytyy monipuolinen
        kattaus tarpeellisia työkaluja.
  cosmetics:
    barber:
      name: Parturi
      desc: Parturi, joka voi muotoilla hiuksesi ja muut pääkarvasi erilaiseksi.
    wardrobe:
      name: Vaatekaappi
      desc: Vaatekaappi mahdollistaa päälläsi olevien kosmeettisten esineiden vaihtamisen
        muihin omistamiisi vaihtoehtoihin.
  trinketry:
    basicTrinketryBench:
      desc: Työpenkki, joka on suunniteltu jalokivien jalostamiseen ja yksinkertaisten
        arvoesineiden tekemiseen.
      name: Simppeli korutyöpenkki
    advancedTrinketryBench:
      desc: Työntekopenkki, jonka läheisyydestä löytyy linssejä, hiomapaperia ja muita
        hyötyesineitä jotka auttavat korutöiden tekemisessä.
      name: Edistynyt korutyöpenkki
    ruinedTrinketryBench:
      desc: Talvenlopun raunioissa on muinainen korutyöpenkki, joka on peittynyt ajan
        saatossa sienten ja sammalen alle.
      name: Raunioitunut korutyöpenkki (simppeli)
    erdwissTrinketryFactory:
      name: Erdwissiläinen korutyötehdas (edistynyt)
      desc: Erdwisen korutyötehtaassa on edistyneitä Myrskyahjosta tuotuja koneita
        jalokivien jalostamiseen.
  tailoring:
    basicLoom:
      name: Simppelit kangaspuut
      desc: Vaatimaton työpaja, josta löytyy tukevat kangaspuut ja paljon käytetyn
        oloinen ompelupöytä.
    advancedLoom:
      name: Edistyneet kangaspuut
      desc: Hyvin varustettu työpaja, jossa on huippuluokan kangaspuut ja hienostuneen
        oloinen ompelupöytä.
maps:
  tiers:
    "basic": Simppeli
    "advanced": Edistynyt
    "legendary": Legendaarinen
    "mythic": Myyttinen
