singulars:
  smithing:
    cursedForge:
      name: Forheksede Smie (Avansert)
      desc: Den forheksede smien bruker sterke flamer fra sjelene rundt. Men dette
        kommer med en pris. Kanskje best å ikke bruke den for mye.
    advancedForge:
      name: Avansert smie
      desc: En mer sofistikert smie, perfekt til å lage intrikate og høykvalitetsgjenstander.
    frozenForge:
      name: Fryst smie
      desc: En smie laget av is med penguindekorasjoner dekorert over hele smia.
    underwaterForge:
      name: Sunken smie (Enkel)
    basicForge:
      name: Enkel smie
      desc: En begynner-nivå smie, perfekt til å lage enkle gjenstander.
  cooking:
    cursedKitchen:
      name: Forhekset kjøkken (Avansert)
    underwaterKitchen:
      name: Sunken kjøkken (Enkel)
      desc: Kjøkken har forskjellige spesialredskaper som kan bukes til å lage matretter
        under vann.
    advancedKitchen:
      name: Avansert kjøkken
      desc: Et godt berustet kjøkken, passende til å lage gourmeretter og kulinariske
        opplevelser.
    basicKitchen:
      name: Enkelt kjøkken
      desc: En enkel kjøkkenbenk, hvor du kan forbrede enkle matretter.
