singulars:
  smithing:
    basicForge:
      desc: Una fucina di livello base, ideale per la creazione di semplici oggetti.
      name: Forgia di base
    advancedForge:
      name: Forgia Avanzata
      desc: Una forgia più sofisticata, perfetta per creazioni complesse e di più
        alta qualità.
    frozenForge:
      name: Forgia Congelata
      desc: Una forgia fatta di ghiaccio con piccole incisioni a forma di pinguini
        su di essa.
    underwaterForge:
      name: Forgia Sottomarina (Base)
      desc: La fucina sottomarina è alimentata da geyser di vapore caldo che forniscono
        calore sufficiente per fondere il metallo.
    cursedForge:
      name: Fucina maledetta (Avanzato)
      desc: La fucina maledetta trae le sue potenti fiamme dagli spiriti che la circondano,
        ma purtroppo questo ha un prezzo. Meglio non usarla troppo.
    heatstrokeMetalworks:
      name: Lavoro del metallo col fuoco (Avanzato)
      desc: La forte e rinomata fucina dell'Arco di Myriadian. Vanta un calore che
        si può percepire anche nel deserto.
  cooking:
    basicKitchen:
      name: Cucina di base
      desc: Una cucina essenziale, dove è possibile preparare pasti semplici e genuini.
    advancedKitchen:
      name: Cucina Avanzata
      desc: Una cucina ben attrezzata, adatta alla cucina gourmet e agli esperimenti
        culinari.
    underwaterKitchen:
      name: Cucina Sottomarina (Base)
      desc: Questa cucina è equipaggiata con vari utensili ideali per cucina cibo
        sott'acqua.
    azurazeraKitchen:
      desc: Una cucina comunitaria con alcuni chef che cercano di condividere le loro
        esperienze culinarie per migliorare.
      name: Cucina Alight (Base)
    cursedKitchen:
      desc: La cucina maledetta ha tutto il necessario per cucinare un piatto, se
        solo il fornello mantenesse una temperatura costante e l'acqua continuasse
        a scorrere.
      name: Cucina maledetta (Avanzato)
    eberhartMansionKitchen:
      name: Cucina della villa Eberhart (Avanzato)
      desc: La famiglia Eberhart dona a chi dona agli altri. La prova della tua dedizione
        alla mensa locale è una ragione più che sufficiente per loro per aprirti le
        porte e aiutarti nella loro cucina condivisa.
  crafting:
    basicWorkshop:
      name: Bottega di base
      desc: Una bottega con attrezzatura di base, progettata per la realizzazione
        di oggetti semplici e pratici.
    advancedWorkshop:
      name: Bottega Avanzata
      desc: Una bottega avanzata, attrezzata per realizzare creazioni complesse e
        versatili.
    tidalWorkshop:
      name: Laboratorio delle maree (Avanzato)
      desc: Un laboratorio sempre influenzato dalle correnti Dispone di tutti gli
        strumenti necessari per realizzare oggetti artigianali.
    cursedWorkshop:
      name: Laboratorio maledetto (Avanzato)
      desc: Il laboratorio maledetto sembra normale a prima vista, ma emana un odore
        di zolfo, marciume e un leggero sentore di limone. È davvero maledetto.
  trinketry:
    ruinedTrinketryBench:
      desc: Tra le rovine di Fine dell'Inverno, un antico banco di bigiotteria giace
        ricoperto di muschio e funghi.
      name: Panchina rovinata per ninnoli (base)
    granularFacetingFacility:
      desc: Una straordinaria struttura dedicata alla bigiotteria che riunisce alcuni
        dei migliori seguaci dell'arte della gemmologia.
      name: Struttura di sfaccettatura granulare (avanzata)
    basicTrinketryBench:
      name: Banco per bigiotteria di base
      desc: Un banco da lavoro, progettato per tagliare gemme e realizzare semplici
        bigiotteria.
    advancedTrinketryBench:
      name: Banco avanzato per la creazione di ninnoli
      desc: Una modesta panca, piena di lenti, carta vetrata e altri strumenti di
        un artigiano che produce ninnoli.
    erdwissTrinketryFactory:
      name: Fabbrica di ninnoli a Erdwiss (Avanzato)
      desc: L'ETF dispone di alcune delle migliori macchine importate da Galeforge
        per il taglio delle gemme.
  tailoring:
    basicLoom:
      desc: Un modesto laboratorio, che ospita un robusto telaio e un tavolo da cucito
        consumato, è pieno di un assortimento di tessuti e strumenti, perfetti per
        sarti in erba desiderosi di imparare l'arte della confezione di abiti.
      name: Telaio base
    advancedLoom:
      name: Telaio avanzato
      desc: Un laboratorio ben attrezzato, che ospita un telaio all'avanguardia e
        un elegante tavolo da cucito, è pieno di una selezione curata di tessuti di
        alta qualità e strumenti specializzati, perfetti per sarti esperti che desiderano
        realizzare capi raffinati.
  carpentry:
    basicSawmill:
      name: Segheria di base
      desc: Un impianto rudimentale per la lavorazione del legname, dove i tronchi
        vengono trasformati in legname grezzo.
    cursedSawmill:
      name: Segheria maledetta (Avanzato)
      desc: La segheria maledetta fa girare una sega così velocemente che temi che
        possa staccarsi. A volte ti sembra che sia lei a tirarti verso di sé, piuttosto
        che i tronchi che vengono tagliati.
    advancedSawmill:
      name: Segheria avanzata
      desc: Una segheria avanzata, in grado di produrre legname di qualità superiore
        con precisione ed efficienza.
    barbantokSawmill:
      name: Segheria di Barbantok (Base)
      desc: Una segheria che si dice sia infestata dal fantasma di Barbantok, un leggendario
        falegname noto per la sua eccezionale maestria.
    underwaterSawmill:
      name: Segheria subacquea (base)
      desc: Una segheria perfetta per lavorare con coralli simili al legno, ma che
        fornisce anche gli strumenti per trasformare qualsiasi tronco in assi.
    sawInHalfMill:
      name: Mulino Saw-in-half (Avanzato)
      desc: La segheria degli halfling è una meraviglia dell'ingegneria, che sfrutta
        il flusso dell'acqua attraverso un acquedotto sottomarino e una sofisticata
        ruota idraulica.
  cosmetics:
    barber:
      name: Barbiere
      desc: Un barbiere che può acconciare i tuoi capelli in modo diverso.
    wardrobe:
      name: Guardaroba
      desc: Accesso al tuo guardaroba, così potrai cambiare il tuo look con qualsiasi
        cosmetico tu possieda.
  misc:
    mysteriousMerchant:
      name: Mercante Misterioso
      desc: Una figura oscura che offre servizi esotici.
maps:
  tiers:
    "basic": Base
    "advanced": Avanzato
    "legendary": Leggendario
    "mythic": Mitico
