singulars:
  smithing:
    basicForge:
      desc: Una fragua elemental, perfecta para fabricar objetos simples.
      name: Fragua Básica
    advancedForge:
      name: Fragua Avanzada
      desc: Una fragua más sofisticada, perfecta para forjar creaciones complicadas
        y de más alta calidad.
    frozenForge:
      name: Fragua Congelada
      desc: Una fragua hecha de hielo con pequeños pingüinos tallados alrededor.
    underwaterForge:
      name: Fragua Submarina (Básica)
      desc: La fragua submarina funciona con géiseres de vapor caliente que proporcionan
        calor suficiente para fundir el metal.
    cursedForge:
      name: Fragua Maldita (Avanzada)
      desc: La forja maldita obtiene sus poderosas llamas de los espíritus que la
        rodean, pero esto tiene un precio. Mejor no usarla demasiado.
    heatstrokeMetalworks:
      desc: La poderosa y aclamada forja del Arco Miriadiano. Su calor se percibe
        incluso en el desierto.
      name: Metalurgia de Golpes de Calor (Avanzado)
  cooking:
    advancedKitchen:
      desc: Una cocina bien equipada, apropiada para experimentos culinarios y una
        cocina gourmet.
      name: Cocina Avanzada
    eberhartMansionKitchen:
      desc: La familia Eberhart ayuda a aquellos que ayudan. Tu dedicación en el comedor
        social es más que suficiente para que te abran las puertas y te ayuden en
        su cocina compartida.
      name: Cocina de la Mansión Eberhart (Avanzada)
    basicKitchen:
      name: Cocina Básica
      desc: Una cocina modesta, donde puedes preparar platos sencillos y saludables.
    underwaterKitchen:
      name: Cocina Submarina (Básica)
      desc: Esta cocina está equipada con diversos utensilios de cocina modificados
        para cocinar bajo el agua.
    azurazeraKitchen:
      desc: Una cocina comunitaria con algunos chefs intentando compartir su experiencia
        de cocina con otros para mejorar.
      name: Cocina Ardiente (Básica)
    cursedKitchen:
      desc: La cocina maldita tiene todo lo necesario para ayudar a cocinar un plato,
        siempre y cuando la estufa se mantuviera a una temperatura constante y el
        agua siguiera corriendo.
      name: Cocina Maldita (Avanzado)
  carpentry:
    advancedSawmill:
      desc: Una fábrica avanzada para el procesado de madera, capaz de producir tablones
        de alta calidad con precisión y eficiencia.
      name: Aserradero Avanzado
    basicSawmill:
      name: Aserradero Básico
      desc: Una rudimentaria instalación para el procesado de madera, donde los troncos
        son transformados en tablones básicos.
    barbantokSawmill:
      name: Aserradero de Barbantok (Básico)
      desc: Un aserradero que dicen está encantado por el fantasma de Barbantok, un
        legendario carpintero que era conocido por su excepcional destreza.
    underwaterSawmill:
      name: Aserradero Submarino (Básico)
      desc: Un aserradero perfecto para trabajar con corales similares a la madera,
        pero que también proporciona herramientas para convertir cualquier tronco
        en tablones.
    sawInHalfMill:
      name: Aserramedio (Avanzado)
      desc: El aserradero de los medianos es una maravilla de la ingeniería, confiando
        en el flujo de agua de un acuaducto subterráneo y una sofisticada noria.
    cursedSawmill:
      name: Aserradero Maldito (Avanzado)
      desc: El aserradero maldito gira tan rápido que temes que se suelte. A veces
        sientes que tira hacia ti en lugar de hacia los troncos que corta.
  crafting:
    basicWorkshop:
      name: Taller Básico
      desc: Un taller básico, diseñado para fabricar objetos simples y prácticos.
    advancedWorkshop:
      name: Taller Avanzado
      desc: Un taller avanzado, equipado para fabricar creaciones complejas y versátiles.
    tidalWorkshop:
      name: Taller de la Marea (Avanzado)
      desc: Un taller siempre influenciado por la corriente. Dispone de todas las
        herramientas necesarias para fabricar.
    cursedWorkshop:
      name: Taller Maldito (Avanzado)
      desc: El taller maldito parece normal al principio, pero huele a azufre, podredumbre
        y un toque de limón. Está, en efecto, maldito.
  cosmetics:
    barber:
      name: Peluquería
      desc: Un peluquero que puede cambiar tu peinado.
    wardrobe:
      name: Vestuario
      desc: Accede a tu vestuario, donde puedes cambiar tu apariencia con cualquier
        objeto cosmético que poseas.
  tailoring:
    basicLoom:
      name: Telar Básico
      desc: Un taller modesto, con un telar robusto y una mesa de coser desgastada,
        lleno con una selección de telas y herramientas perfecto para sastres incipientes
        deseosos de aprender el arte de la costura.
    advancedLoom:
      name: Telar Avanzado
      desc: Un taller bien equipado, con un telar de última generación y una elegante
        mesa de coser, lleno con un surtido seleccionado de telas premium y herramientas
        especializadas perfecto para sastres experimentados que busquen crear trajes
        exquisitos.
  trinketry:
    basicTrinketryBench:
      name: Banco de Joyería Básico
      desc: Un banco de trabajo, diseñado para cortar gemas y hacer joyas simples.
    ruinedTrinketryBench:
      name: Banco de Joyería en ruinas (Básico)
      desc: En las ruinas de Fin de Invierno, un vetusto banco de joyería se encuentra
        cubierto de musgo y hongos.
    advancedTrinketryBench:
      name: Banco de Joyería Avanzado
      desc: Un banco modesto, lleno de lentes, papel de lija y otras herramientas
        de un joyero experimentado.
    erdwissTrinketryFactory:
      name: Fábrica de Joyas de Erdwiss (Avanzado)
      desc: La FJE tiene alguna de las mejores máquinas importadas de Forjavendaval
        para el corte de gemas.
    granularFacetingFacility:
      name: Instalación de Facetado Granular (Avanzada)
      desc: Una destacada instalación de joyería que reúne a algunos de los mejores
        seguidores del arte de la gemología.
maps:
  tiers:
    "basic": Básico
    "advanced": Avanzado
    "legendary": Legendario
    "mythic": Mítico
