singulars:
  smithing:
    basicForge:
      name: Basissmederij
      desc: Een beginnerssmederij, ideaal voor het maken van eenvoudige voorwerpen.
    advancedForge:
      name: Geavanceerde Smederij
      desc: Een wat complexere smederij, perfect voor het fabriceren van ingewikkelde
        creaties van hogere kwaliteit.
    frozenForge:
      name: Bevroren Smederij
      desc: Een smederij gemaakt van ijs volledig gedecoreerd met kleine uitsnedes
        van pinguïns.
    underwaterForge:
      name: Onderwatersmederij (Basis)
      desc: De onderwatersmederij functioneert door hete stoomgeisers die genoeg hitte
        opwekken om metaal te smelten.
    cursedForge:
      name: Vervloekte Smidse (Geavanceerd)
      desc: De vervloekte smidse haalt zijn krachtige vlammen uit de geesten eromheen,
        maar helaas is dat niet voor niets. Beter niet te veel gebruiken.
    heatstrokeMetalworks:
      name: Zonnesteek Metaalwerken (Geavanceerd)
      desc: De sterke en geroemde smidse van de Myriaadse Arc. Het straalt een hitte
        uit die je zelfs in de woestijn nog kunt voelen.
  cooking:
    basicKitchen:
      name: Basiskeuken
      desc: Een bescheiden keukenopstelling, waar je simpele en gezonde maaltijden
        kunt bereiden.
    advancedKitchen:
      name: Geavanceerde Keuken
      desc: Een goed uitgeruste keuken, geschikt voor gastronomisch keuken en culinaire
        experimenten.
    underwaterKitchen:
      name: Onderwaterkeuken (Basis)
      desc: Deze keuken is uitgerust met verschillend keukengerei, aangepast om onderwater
        gerechten te kunnen maken.
    eberhartMansionKitchen:
      name: Eberthart Landgoed Keuken (Geavanceerd)
      desc: De Eberhart-familie geeft aan hen die aan anderen geven. Het bewijs van
        je toewijding aan de lokale Gaarkeuken geeft meer dan genoeg reden voor ze
        om hun deuren te openen en je te helpen in hun gedeelde keukenruimte.
    azurazeraKitchen:
      name: Verlichte Keuken (Basis)
      desc: Een gemeenschapskeuken waar een paar chefs hun kokservaring met elkaar
        delen.
    cursedKitchen:
      name: Vervloekte Keuken (Geavanceerd)
      desc: De vervloekte keuken heeft alles wat je nodig hebt om een gerecht te bereiden.
        Bleef het fornuis maar op een consistente temperatuur, en kwam er maar consistent
        water uit de kraan.
  crafting:
    basicWorkshop:
      name: Basis Werkplaats
      desc: Een basis werkplaatsinrichting, ontworpen voor het maken van simpele en
        praktische voorwerpen.
    advancedWorkshop:
      name: Geavanceerde Werkplaats
      desc: Een geavanceerde werkplaats, uitgerust voor het maken van complexe en
        veelzijdige ambachtelijke creaties.
    tidalWorkshop:
      name: Getijdenwerkplaats (Geavanceerd)
      desc: Een werkplaats die altijd beïnvloed wordt door de stroming. Het heeft
        al het gereedschap wat nodig is voor ambachtelijk geknutsel.
    cursedWorkshop:
      name: Vervloekte Werkplaats (Geavanceerd)
      desc: In eerste instantie is er niks vreemds te merken aan de vervloekte werkplaats,
        maar het ruikt er naar zwavel, verrotting, en een beetje citroen. Inderdaad
        vervloekt.
  carpentry:
    basicSawmill:
      name: Basiszagerij
      desc: Een rudimentaire houtverwerkingsfaciliteit, waar boomstammen getransformeerd
        worden tot basaal timmerhout.
    advancedSawmill:
      name: Geavanceerde Zagerij
      desc: Een geavanceerde houtverwerkingsmolen, in staat om met precisie en efficiëntie
        timmerhout te maken van hogere kwaliteit.
    barbantokSawmill:
      name: Zagerij van Barbantok (Basis)
      desc: Een zagerij waarvan gezegd wordt dat het behekst is door de geest van
        Barbantok, een legendarische timmerman die bekend staat om zijn exceptionele
        vakmanschap.
    underwaterSawmill:
      name: Onderwaterzagerij (Basis)
      desc: Een zagerij die perfect is voor het werken met houtachtige koralen, maar
        die ook uitgerust is om planken te maken van stukken hout.
    sawInHalfMill:
      name: Zaag-Door-De-Helft Zagerij (Geavanceerd)
      desc: De halfling-zagerij is een wonder van techniek. Hij vertrouwt op de stroom
        van water door een onderwater-aquaduct en een geavanceerd waterrad.
    cursedSawmill:
      name: Vervloekte Zagerij (Geavanceerd)
      desc: De vervloekte zagerij draait een cirkelzaag zo snel rond dat je bang bent
        dat het losraakt. Soms voelt het alsof het jouw kant op trekt in plaats van
        naar het hout dat doorgezaagd wordt.
  cosmetics:
    barber:
      name: Kapper
      desc: Een kapper die je een ander kapsel kan geven.
    wardrobe:
      name: Kledingkast
      desc: Toegang tot je kledingkast, waarmee je jouw uiterlijk kunt aanpassen met
        cosmetica die je bezit.
  tailoring:
    advancedLoom:
      name: Geavanceerd Weefgetouw
      desc: Deze goed ingerichte werkplaats, waarin een top qualiteit weefgetouw en
        een elegante naai tafel staan, is gevuld met een speciale selectie stoffen
        en gespecialiseerd gereedschap die zeer geschikt zijn voor ervaren kleermakers
        om uitmuntende kleding mee te maken.
    basicLoom:
      desc: Deze simpele werkplaats, waarin een stevig weefgetouw en een goed gebruikte
        naaitafel staan, is gevuld met een assortiment van stoffen en gereedschap
        welke perfect zijn voor leergierige nieuwe kleermakers.
      name: Basis Weefgetouw
  trinketry:
    basicTrinketryBench:
      name: Basis Sierraderijbank
      desc: Een werkbank, ontworpen voor het slijpen van edelstenen en het maken van
        simpele sierraden.
    erdwissTrinketryFactory:
      desc: De ESF heeft enkele van de beste machines geïmporteerd vanuit Guuroven,
        die gebruikt worden voor het slijpen van edelstenen.
      name: Erdweis Sierraderijfabriek (Geavanceerd)
    ruinedTrinketryBench:
      name: Verwoeste Sierraderijwerkbank (Basis)
      desc: In de ruïnes van Winterseind bevindt zich een Sierraderijwerkbank bedekt
        met mos en paddestoelen.
    advancedTrinketryBench:
      name: Geavanceerde Sierraderijwerkbank
      desc: Een bescheiden werkbank, gevuld met loepjes, schuurpapier, en ander gereedschap
        van een gevorderde sierraadmaker.
    granularFacetingFacility:
      name: Granulaire Facetteringsfaciliteit (Geavanceerd)
      desc: Een buitengewone sierraderijfaciliteit waar de meest fanatieke volgelingen
        van de sierradenkunst op afkomen.
maps:
  tiers:
    "basic": Basis
    "advanced": Geavanceerd
    "legendary": Legendarisch
    "mythic": Mythisch
