singulars:
  smithing:
    basicForge:
      name: Forja Básica
      desc: Uma forja básica, ideal para fabricar artigos simples.
    frozenForge:
      name: Forja Congelada
      desc: Uma forja feita de gelo com pequenas esculturas de pinguins em toda a
        sua extensão.
    underwaterForge:
      name: Forja Subaquática (Básica)
    advancedForge:
      name: Forja Avançada
      desc: Uma forja mais sofisticada, perfeita para criar peças complexas e de alta
        qualidade.
  cooking:
    basicKitchen:
      name: Cozinha básica
      desc: Uma cozinha modesta, onde pode preparar refeições simples e saudáveis.
    advancedKitchen:
      name: Cozinha Avançada
      desc: Uma cozinha bem equipada, ideal para cozinha gourmet e experiências gastronómicas.
    underwaterKitchen:
      name: Cozinha Subaquática (Básica)
      desc: Esta cozinha está equipada com diversos utensílios de cozinha adaptados
        para a preparação de alimentos debaixo de água.
    eberhartMansionKitchen:
      name: Cozinha da Mansão Eberhart (Avançado)
