singulars:
  carpentry:
    advancedSawmill:
      desc: Une usine de transformation du bois de pointe, capable de produire du
        bois de construction de qualité supérieure avec précision et efficacité.
      name: Scierie avancée
    basicSawmill:
      desc: Une installation rudimentaire pour travailler le bois. Les bûches y sont
        transformées en bois de construction basique.
      name: Scierie basique
    barbantokSawmill:
      name: Scierie de Barbantok
      desc: D'après les rumeurs, cette scierie serait hantée par le fantôme de Barbantok,
        un menuisier légendaire connu pour son savoir-faire extraordinaire.
    underwaterSawmill:
      name: Scierie sous-marine
      desc: Cette scierie est parfaite pour travailler avec des coraux, elle fournit
        également des outils pour transformer n'importe quelle bûche en planches.
    sawInHalfMill:
      desc: La scierie halfeline est une merveille d'ingénierie, canalisant la force
        du courant grâce à un aqueduc sous-marin et une roue à aubes sophistiquée.
      name: Scie-à-moitié (Avancé)
  smithing:
    frozenForge:
      desc: Une forge faite de glace avec de petites gravures de pingouins un peu
        partout.
      name: Forge gelée
    basicForge:
      desc: Une forge d'entrée de gamme, idéale pour les débutants tentant de fabriquer
        des objets simples.
      name: Forge basique
    advancedForge:
      name: Forge améliorée
      desc: Une forge plus sophistiquée, parfaite pour confectionner des créations
        complexes et de meilleure qualité.
    underwaterForge:
      name: Forge sous-marine (Basique)
      desc: La forge sous-marine fonctionne grâce à des geysers de vapeurs brûlante,
        fournissant assez de chaleur pour fondre le métal.
  cooking:
    basicKitchen:
      name: Cuisine basique
      desc: Une installation de cuisine modeste. Il est possible d'y préparer des
        repas simples et sains.
    advancedKitchen:
      name: Cuisine améliorée
      desc: Une cuisine bien équipée, adaptée aux expériences culinaires et à la cuisine
        gastronomique.
    underwaterKitchen:
      name: Cuisine sous-marine (Basique)
      desc: Cette cuisine est remplie d'équipements permettant de faire à manger sous
        l'eau.
    eberhartMansionKitchen:
      name: Cuisine de la Maison Eberhart (Avancée)
      desc: La famille Eberhart est généreuse envers les altruistes. La preuve de
        votre dévouement à la soupe populaire locale est une raison plus que suffisante
        pour qu'ils vous ouvrent leurs portes et vous permettent d'utiliser leur cuisine.
  crafting:
    basicWorkshop:
      desc: Un atelier tout ce qu'il y a de plus basique, conçu pour fabriquer des
        objets simples et pratiques.
      name: Atelier basique
    advancedWorkshop:
      name: Atelier amélioré
      desc: Un atelier amélioré et bien équipé pour réaliser des créations complexes
        et polyvalentes.
    tidalWorkshop:
      name: Atelier des marées (Avancé)
      desc: Un atelier rythmé par le courant. Il possède tous les outils nécessaires
        pour travailler.
  cosmetics:
    barber:
      name: Coiffeur
      desc: Un coiffeur qui peut changer votre coupe de cheveux.
    wardrobe:
      name: Garde-robe
      desc: Ouvrez votre garde-robe pour pouvoir changer de tenue et porter n'importe
        quel cosmétique que vous possédez.
  tailoring:
    basicLoom:
      name: Atelier de couture basique
      desc: Un atelier modeste, équipé d'une solide machine à coudre et d'une table
        de couture usée, rempli d'un ensemble de tissus et d'outils, parfait pour
        les couturiers en herbe désireux d'apprendre l'art de la création de vêtements.
    advancedLoom:
      name: Atelier de couture avancé
      desc: Un atelier haut de gamme, équipé d'une machine à coudre à la pointe de
        la technologie et d'un table de couture élégante, rempli d'un ensemble soigneusement
        sélectionné de tissus de luxe et d'outils spécialisés, parfait pour les couturiers
        expérimentés désireux de fabriquer des vêtements exquis.
  trinketry:
    basicTrinketryBench:
      name: Etabli de Bimbeloterie basique
      desc: Un établi conçu pour tailler des gemmes et fabriquer des bibelots simples.
    advancedTrinketryBench:
      desc: Un modeste établi, couvert de lentilles, de papier de verre et d'autres
        outils utiles pour un compagnon bricoleur..
      name: Établi de Joaillerie Avancé
    ruinedTrinketryBench:
      name: Établi de Joaillerie en Ruine (Basique)
      desc: Dans les ruines du Repos de l'Hiver, un ancien établi de joaillerie reste,
        couvert de mousse et de champignons.
    erdwissTrinketryFactory:
      desc: L'usine de Joaillierie d'Erdwise possède des machines extrêmement précises
        pour tailler les gemmes, importées depuis Forge-Tempête.
      name: Usine de Joaillerie d'Erdwise (Avancé)
maps:
  tiers:
    'basic': Basique
    'advanced': Avancé
    'legendary': Légendaire
    'mythic': Mythique
