singulars:
  carpentry:
    advancedSawmill:
      name: Gelişmiş Bıçkıhane
      desc: Hassasiyet ve verimlilikle yüksek kaliteli ahşap üretme kapasitesine sahip
        olan gelişmiş bir kereste imalathanesi.
    basicSawmill:
      name: Basit Bıçkıhane
      desc: Kütüklerin basit kerestelere çevrildiği ilkel bir odun işleme tesisi.
    barbantokSawmill:
      name: Barbantok Bıçkıhanesi
      desc: Emsalsiz hünerleriyle tanınmış efsanevi marangoz "Barbantok'un Hayaleti"nin
        musallat olduğu söylenen bir bıçkıhane.
    underwaterSawmill:
      name: Su Altı Bıçkıhanesi
      desc: Odunsu mercan parçaları üzerinde çalışmak için mükemmel bir bıçkıhane.
        Ayrıca başka kütükleri kalasa çevirebilen aletler de bulunur.
    sawInHalfMill:
      name: Buçkuhane
      desc: Buçukluk bıçkıhanesi bir mühendislik harikasıdır. Su altındaki su kemerinden
        geçen akıntıyı ve gelişmiş bir su çarkını kullanarak çalışır.
    cursedSawmill:
      name: Lanetli Bıçkıhane
      desc: Bu lanetli bıçkıhanede testereler o kadar hızlı döner ki acaba yerinden
        fırlar mı diye düşünmeden edemezsin. Durdukları yerde kütükleri kesmek yerine
        ara sıra sana doğru yaklaşıyorlar sanki.
  cooking:
    advancedKitchen:
      name: Gelişmiş Mutfak
      desc: Gurmelerin ağızlarına layık yemek denemeleri yapabileceğin tam teşekküllü
        bir mutfak.
    basicKitchen:
      name: Basit Mutfak
      desc: Kolay ama besleyici yemekler hazırlayabileceğin sade bir mutfak düzeni.
    eberhartMansionKitchen:
      desc: Eberhart ailesi, imkanlarını hayırseverlerin yardımına sunar. Yerel aşevine
        yaptığın katkıların ispatı, kapılarını sonuna kadar açarak ortak mutfaklarında
        yardımcı olmaları için yeter de artar bile.
      name: Eberhart Köşkü Mutfağı
    underwaterKitchen:
      name: Su Altı Mutfağı
      desc: Bu mutfakta su altında yemek pişirmeyi kolaylaştıran çeşitli mutfak aletleri
        bulunur.
    azurazeraKitchen:
      name: Nurlu Mutfak
      desc: Becerilerini geliştirmek için aşçıların tecrübelerini birbirleriyle paylaştıkları
        bir halk mutfağı.
    cursedKitchen:
      name: Lanetli Mutfak
      desc: Yemek yapmak için gereken her şey bu lanetli mutfakta bulunur. Keşke bir
        de sular ikide bir kesilip durmasa ve fırının derecesi kendi kendine zırt
        pırt değişmese.
  crafting:
    advancedWorkshop:
      name: Gelişmiş Atölye
      desc: Karmaşık ve çok işlevli eşyalar üretmek için donatılmış gelişmiş bir atölye.
    basicWorkshop:
      desc: Basit ve pratik eşyalar üretmek için tasarlanmış temel bir atölye kurulumu.
      name: Basit Atölye
    tidalWorkshop:
      name: Gelgit Atölyesi
      desc: Her zaman akıntıların etkisinde bulunan bir atölye. Bir şeyler üretmek
        için gereken her alete sahip.
    cursedWorkshop:
      name: Lanetli Atölye
      desc: Bu lanetli atölye ilk bakışta normalmiş gibi görünse de burnuna sülfür,
        küf ve bir tık limon kokusu geliyor. Sahiden de lanetliymiş.
  smithing:
    advancedForge:
      desc: Çok yönlü bir demirhane. Çetrefilli ve yüksek kaliteli eserlere şekil
        vermek için mükemmel.
      name: Gelişmiş Demirhane
    basicForge:
      desc: Karmaşık olmayan eşyaları üretmek için ideal, başlangıç düzeyinde bir
        demirhane.
      name: Basit Demirhane
    frozenForge:
      desc: Her yanında küçük penguen oymaları bulunan buzdan yapılma bir demirhane.
      name: Donmuş Demirhane
    underwaterForge:
      desc: Su altı demirhanesi, metali eritmek için gereken ısıyı sağlayan sıcak
        buhar gayzerleriyle çalışır.
      name: Su Altı Demirhanesi
    cursedForge:
      name: Lanetli Demirhane
      desc: Bu lanetli demirhane kuvvetli ateşini etrafta gezinen ruhlardan çeker.
        Ne yazık ki bunun bir bedeli vardır. En iyisi fazla kullanmamak.
    heatstrokeMetalworks:
      name: Güneşe Çarptıran Dökümhane
      desc: Miriadyan Kemeri'nin meşhur sağlam demirhanesi. Öyle bir yanar ki sıcaklığı
        çölde bile hissedilir.
  cosmetics:
    wardrobe:
      name: Gardırop
      desc: Gardırobuna erişip sahip olduğun kozmetik eşyaları kullanarak görünümünü
        değiştirebilirsin.
    barber:
      name: Berber
      desc: Saçını farklı bir modele çevirebilen bir berber.
  trinketry:
    ruinedTrinketryBench:
      desc: Zemheridibi'nin yıkıntıları arasında kalmış, yosun ve mantarlarla kaplı
        antika bir takı tezgahı.
      name: Harap Takı Tezgahı
    erdwissTrinketryFactory:
      desc: ETF'de cevher kesmek için Boraocak'tan getirtilen dünyanın en iyi makineleri
        bulunur.
      name: Erdwise Takı Fabrikası
    basicTrinketryBench:
      name: Basit Takı Tezgahı
      desc: Cevher kesmek ve sade takılar yapmak için tasarlanmış bir çalışma tezgahı.
    advancedTrinketryBench:
      name: Gelişmiş Takı Tezgahı
      desc: Büyüteçler, zımparalar ve usta bir takıcının ihtiyacı olan diğer aletlerle
        dolu sade bir tezgah.
    granularFacetingFacility:
      name: Granül Kesim Tesisi
      desc: En iyi cevher işçiliği ustalarının bazılarını bir araya getirmiş olan
        olağanüstü bir takıcılık tesisi.
  tailoring:
    basicLoom:
      name: Basit Terzihane
      desc: Sağlam bir dokuma tezgahı ile yıpranmış bir dikiş masası bulunan sade
        bir terzihane. O kadar çok kumaş çeşidi ve aletlerle dolu ki kıyafet yapma
        sanatına atılmak isteyen hevesli terziler için mükemmel bir yer.
    advancedLoom:
      name: Gelişmiş Terzihane
      desc: Teknoloji harikası bir dokuma tezgahı ile şık bir dikiş masası bulunan
        dayalı döşeli bir terzihane. Özenle seçilmiş pahalı kumaşlar ve hassas aletlerle
        dolu olduğundan seçkin giysiler üretmek isteyen deneyimli terziler için mükemmel
        bir yer.
maps:
  tiers:
    "basic": Basit
    "advanced": Gelişmiş
    "legendary": Efsanevi
    "mythic": Mitolojik
