singulars:
  smithing:
    advancedForge:
      name: Продвинутая кузница
      desc: Более передовая кузница, идеально подходящая для создания замысловатых
        и высококачественных творений.
    frozenForge:
      name: Замороженная кузница
      desc: Ледяная кузница с резными пингвинами, вырезанными по всему периметру.
    underwaterForge:
      name: Подводная кузница (Начальный уровень)
      desc: Подводная кузница работает за счет гейзеров горячего пара, дающих достаточно
        тепла, чтобы расплавить металл.
    basicForge:
      name: Базовая кузница
      desc: Кузница начального уровня, идеально подходящая для изготовления простых
        предметов.
    heatstrokeMetalworks:
      desc: Мощная и знаменитая кузница Мириадской Арки. Она излучает такое тепло,
        что его чувствуешь даже в пустыне.
      name: Кузница «Огненный металл» (продвинутая)
    cursedForge:
      name: Проклятая кузница (продвинутая)
      desc: Проклятая кузница черпает свою мощную силу из окружающих её духов, но,
        к сожалению, за это приходится платить. Лучше не пользоваться ею слишком часто.
  cooking:
    basicKitchen:
      name: Начальная кухня
      desc: Скромная кухня, где можно готовить простые и полезные блюда.
    advancedKitchen:
      name: Продвинутая кухня
      desc: Хорошо оборудованная кухня, подходящая для приготовления блюд для гурманов
        и кулинарных опытов.
    eberhartMansionKitchen:
      desc: Семья Эберхарт помогает тем, кто помогает другим. Доказательство вашей
        преданности местной столовой — более чем достаточная причина для них открыть
        свои двери и позволить вам пользоваться их общим кухонным пространством.
      name: Кухня Эберхарта (продвинутая)
    underwaterKitchen:
      name: Подводная кухня (Начальный уровень)
      desc: Кухня оборудована различными инструментами, приспособленными для приготовления
        пищи под водой.
    azurazeraKitchen:
      name: Кухня Просветления
      desc: Общественная кухня, где повара пытаются делиться друг с другом кулинарным
        опытом для совершенствования.
    cursedKitchen:
      name: Проклятая кухня (продвинутая)
      desc: На проклятой кухне есть всё необходимое для приготовления блюд, если бы
        только плита держала постоянную температуру, а вода не переставала течь.
  carpentry:
    advancedSawmill:
      desc: Продвинутый уровень деревообработки, позволяющий производить пиломатериалы
        высокого качества с высокой точностью и эффективностью.
      name: Продвинутая лесопилка
    underwaterSawmill:
      desc: Лесопилка, которая идеально подходит для работы с древесными кораллами,
        а также предоставляет инструменты для создания досок из любых бревен.
      name: Подводная лесопилка (Начальный уровень)
    basicSawmill:
      desc: Простейшее деревообрабатывающее предприятие, где бревна превращаются в
        пиломатериалы.
      name: Базовая Лесопилка
    barbantokSawmill:
      name: Лесопилка Барбантока (Начальный уровень)
      desc: Лесопилка, в которой, по преданию, обитает призрак Барбантока, легендарного
        плотника, известного своим исключительным мастерством.
    sawInHalfMill:
      desc: 'Лесопилка полуросликов — чудо инженерной мысли: она работает благодаря
        потоку воды, проходящему через подводный водовод и сложное водяное колесо.'
      name: Лесопилка полуросликов (продвинутая)
    cursedSawmill:
      name: Проклятая лесопилка (продвинутая)
      desc: Пила заколдованной лесопилки вращается с такой скоростью, что, кажется,
        вот‑вот сорвётся с креплений. Ты почти чувствуешь, как она тянет тебя к себе,
        а не брёвна к лезвию.
  cosmetics:
    barber:
      desc: Парикмахер, который может поменять ваш имидж.
      name: Парикмахерская
    wardrobe:
      name: Гардероб
      desc: Доступ к вашему гардеробу, чтобы вы могли менять свой образ под любые
        косметические предметы.
  crafting:
    basicWorkshop:
      desc: Базовая мастерская, предназначенная для изготовления простых и практичных
        предметов.
      name: Базовая мастерская
    tidalWorkshop:
      desc: Мастерская, которая всегда находится под влиянием течений. В ней есть
        все инструменты, необходимые для изготовления вещей.
      name: Мастерская приливов (продвинутая)
    advancedWorkshop:
      name: Продвинутая мастерская
      desc: Продвинутая мастерская, оборудованная для изготовления сложных и многогранных
        творений.
    cursedWorkshop:
      name: Проклятая мастерская (продвинутая)
      desc: Проклятая мастерская кажется обычной на первый взгляд, но пахнет серой,
        гнилью и чуть-чуть лимоном. Она действительно проклята.
  trinketry:
    ruinedTrinketryBench:
      desc: В руинах Зимнего Края стоит древний верстак для ювелирных дел, покрытый
        мхом и грибами.
      name: Разрушенный ювелирный верстак (Начальный уровень)
    erdwissTrinketryFactory:
      name: Ювелирный цех Эрдвайса (продвинутый)
      desc: В цеху установлены самые лучшие станки, привезенные из Кузни ветров для
        огранки самоцветов.
    basicTrinketryBench:
      name: Базовый ювелирный верстак
      desc: Верстак для огранки самоцветов и создания простых безделушек.
    advancedTrinketryBench:
      name: Продвинутый ювелирный верстак
      desc: Скромный верстак, заваленный линзами, наждачной бумагой и прочими инструментами
        подмастерья-ювелира.
    granularFacetingFacility:
      name: Цех тонкой огранки (продвинутый)
      desc: Высокотехнологичный ювелирный цех, собирающий вокруг себя лучших представителей
        ювелирного дела.
  tailoring:
    basicLoom:
      desc: Скромная мастерская с прочным ткацким станком и изношенным швейным столом
        заполнена ассортиментом тканей и инструментов, идеально подходящих для начинающих
        портных, желающих научиться швейному искусству.
      name: Базовый ткацкий станок
    advancedLoom:
      name: Продвинутый ткацкий станок
      desc: В хорошо оборудованной мастерской с современным ткацким станком и элегантным
        швейным столом собраны ткани премиум-класса и специализированные инструменты,
        идеально подходящие для опытных портных, стремящихся создавать изысканную
        одежду.
maps:
  tiers:
    "basic": Базовый
    "advanced": Продвинутый
    "legendary": Легендарный
    "mythic": Мифический
