singulars:
  smithing:
    advancedForge:
      name: Продвинутая кузница
      desc: Более передовая кузница, идеально подходящая для создания замысловатых
        и высококачественных творений.
    frozenForge:
      name: Замороженная кузница
      desc: Ледяная кузница с резными пингвинами, вырезанными по всему периметру.
    underwaterForge:
      name: Подводная кузница (Начальный уровень)
      desc: Подводная кузница работает за счет гейзеров горячего пара, дающих достаточно
        тепла, чтобы расплавить металл.
    basicForge:
      name: Базовая кузница
      desc: Кузница начального уровня, идеально подходящая для изготовления простых
        предметов.
  cooking:
    basicKitchen:
      name: Начальная кухня
      desc: Скромная кухня, где можно готовить простые и полезные блюда.
    advancedKitchen:
      name: Продвинутая кухня
      desc: Хорошо оборудованная кухня, подходящая для приготовления блюд для гурманов
        и кулинарных опытов.
    eberhartMansionKitchen:
      desc: Семья Эберхарт помогает тем, кто помогает другим. Докажи свою преданность
        местной Благотворительной кухне — это более чем достаточная причина для того,
        чтобы они открыли свои двери и позволили Вам пользоваться их общим кухонным
        пространством.
      name: Кухня особняка Эберхарта (Продвинутый уровень)
    underwaterKitchen:
      name: Подводная кухня (Начальный уровень)
      desc: Кухня оборудована различными инструментами, приспособленными для приготовления
        пищи под водой.
  carpentry:
    advancedSawmill:
      desc: Продвинутый уровень деревообработки, позволяющий производить пиломатериалы
        высокого качества с высокой точностью и эффективностью.
      name: Продвинутая Лесопилка
    underwaterSawmill:
      desc: Лесопилка, которая идеально подходит для работы с древесными кораллами,
        а также предоставляет инструменты для создания досок из любых бревен.
      name: Подводная лесопилка (Начальный уровень)
    basicSawmill:
      desc: Простейшее деревообрабатывающее предприятие, где бревна превращаются в
        пиломатериалы.
      name: Базовая Лесопилка
    barbantokSawmill:
      name: Лесопилка Барбантока (Начальный уровень)
      desc: Лесопилка, в которой, по преданию, обитает призрак Барбантока, легендарного
        плотника, известного своим исключительным мастерством.
    sawInHalfMill:
      desc: 'Лесопилка полуросликов — чудо инженерной мысли: она работает благодаря
        потоку воды, проходящему через подводный водовод и сложное водяное колесо.'
      name: Лесопилка полуросликов (продвинутая)
  cosmetics:
    barber:
      desc: Парикмахер, который может поменять ваш имидж.
      name: Парикмахерская
    wardrobe:
      name: Гардероб
      desc: Доступ к вашему гардеробу, чтобы вы могли менять свой образ под любые
        косметические предметы.
  crafting:
    basicWorkshop:
      desc: Базовая мастерская, предназначенная для изготовления простых и практичных
        предметов.
      name: Базовая мастерская
    tidalWorkshop:
      desc: Мастерская, которая всегда находится под влиянием течений. В ней есть
        все инструменты, необходимые для изготовления вещей.
      name: Мастерская приливов и отливов (Продвинутый уровень)
    advancedWorkshop:
      name: Продвинутая мастерская
      desc: Продвинутая мастерская, оборудованная для изготовления сложных и многогранных
        творений.
  trinketry:
    ruinedTrinketryBench:
      desc: В руинах Зимнего Края стоит древний верстак для ювелирных дел, покрытый
        мхом и грибами.
      name: Разрушенный ювелирный верстак (Начальный уровень)
    erdwissTrinketryFactory:
      name: Ювелирная фабрика Эрдвайса (Продвинутый уровень)
      desc: На фабрике установлены самые лучшие станки, привезенные из Кузни ветров
        для огранки самоцветов.
    basicTrinketryBench:
      name: Базовый ювелирный верстак
      desc: Верстак для огранки самоцветов и создания простых безделушек.
    advancedTrinketryBench:
      name: Продвинутый ювелирный верстак
      desc: Скромный верстак, заваленный линзами, наждачной бумагой и прочими инструментами
        подмастерья-ювелира.
  tailoring:
    basicLoom:
      desc: Скромная мастерская с прочным ткацким станком и изношенным швейным столом
        заполнена ассортиментом тканей и инструментов, идеально подходящих для начинающих
        портных, желающих научиться швейному искусству.
      name: Базовый ткацкий станок
    advancedLoom:
      name: Продвинутый ткацкий станок
      desc: В хорошо оборудованной мастерской с современным ткацким станком и элегантным
        швейным столом собраны ткани премиум-класса и специализированные инструменты,
        идеально подходящие для опытных портных, стремящихся создавать изысканную
        одежду.
maps:
  tiers:
    "basic": Базовый
    "advanced": Продвинутый
    "legendary": Легендарный
    "mythic": Мифический
